<?php
declare(strict_types=1);
require_once __DIR__.'/../configs/config.php';
header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');
function respond(bool $ok,array $data=[],int $status=200):never{http_response_code($status);echo json_encode(['ok'=>$ok]+$data,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
if(empty($_SESSION['usuario_id']))respond(false,['message'=>'Sessão expirada.'],401);
require_once __DIR__.'/../configs/social_schema.php';ensureSocialSchema($pdo);$uid=(int)$_SESSION['usuario_id'];
if(empty($_SESSION['social_csrf']))$_SESSION['social_csrf']=bin2hex(random_bytes(24));
function input():array{if(str_contains($_SERVER['CONTENT_TYPE']??'','application/json'))return json_decode(file_get_contents('php://input'),true)?:[];return $_POST;}
function requireCsrf(array $d):void{if(!hash_equals((string)($_SESSION['social_csrf']??''),(string)($d['csrf']??'')))respond(false,['message'=>'Token de segurança inválido.'],403);}
function canCreate(PDO $pdo,int $uid):bool{if(strcasecmp((string)($_SESSION['usuario_tipo']??''),'Administrador')===0)return true;$s=$pdo->prepare("SELECT u.is_community_user OR EXISTS(SELECT 1 FROM usuario_roles ur JOIN roles r ON r.id_role=ur.id_role WHERE ur.id_usuario=u.id_usuario AND r.slug IN('comunitario','administrador')) FROM usuario u WHERE u.id_usuario=?");$s->execute([$uid]);return (bool)$s->fetchColumn();}
function member(PDO $pdo,int $chat,int $uid):void{$s=$pdo->prepare('SELECT 1 FROM social_chat_membros WHERE id_chat=? AND id_usuario=?');$s->execute([$chat,$uid]);if(!$s->fetchColumn())respond(false,['message'=>'Você não participa deste chat.'],403);}
function uploadMedia(array $file,string $kind):array{if(($file['error']??UPLOAD_ERR_NO_FILE)===UPLOAD_ERR_NO_FILE)return [null,null,null];if(($file['error']??1)!==UPLOAD_ERR_OK)respond(false,['message'=>'Falha no upload.'],422);$max=$kind==='sticker'?2*1024*1024:8*1024*1024;if(($file['size']??0)>$max)respond(false,['message'=>$kind==='sticker'?'Figurinha deve ter até 2 MB.':'Imagem deve ter até 8 MB.'],422);$mime=(new finfo(FILEINFO_MIME_TYPE))->file($file['tmp_name']);$allowed=$kind==='sticker'?['image/png'=>'png','image/webp'=>'webp','image/gif'=>'gif']:['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp','image/gif'=>'gif'];if(!isset($allowed[$mime]))respond(false,['message'=>'Formato de mídia não permitido.'],422);$dir=dirname(__DIR__,2).'/static/uploads/social';if(!is_dir($dir)&&!mkdir($dir,0775,true))respond(false,['message'=>'Armazenamento indisponível.'],500);$name=bin2hex(random_bytes(18)).'.'.$allowed[$mime];if(!move_uploaded_file($file['tmp_name'],$dir.'/'.$name))respond(false,['message'=>'Não foi possível salvar a mídia.'],500);return ['../static/uploads/social/'.$name,$mime,(int)$file['size']];}
function uploadPostMedia(array $file,bool $communityOnly=false):array{if(($file['error']??UPLOAD_ERR_NO_FILE)===UPLOAD_ERR_NO_FILE)return [null,null];if(($file['error']??1)!==UPLOAD_ERR_OK)respond(false,['message'=>'Falha no envio da mídia.'],422);$mime=(new finfo(FILEINFO_MIME_TYPE))->file($file['tmp_name']);$allowed=['image/jpeg'=>['jpg','imagem',8*1024*1024],'image/png'=>['png','imagem',8*1024*1024],'image/webp'=>['webp','imagem',8*1024*1024],'video/mp4'=>['mp4','video',40*1024*1024]];if(!$communityOnly){$allowed['image/gif']=['gif','imagem',8*1024*1024];$allowed['video/webm']=['webm','video',40*1024*1024];}if(!isset($allowed[$mime]))respond(false,['message'=>$communityOnly?'Use JPG, PNG, WebP ou MP4.':'Use JPG, PNG, WebP, GIF, MP4 ou WebM.'],422);[$ext,$type,$max]=$allowed[$mime];if(($file['size']??0)>$max)respond(false,['message'=>$type==='video'?'O vídeo deve ter até 40 MB.':'A imagem deve ter até 8 MB.'],422);$dir=dirname(__DIR__,2).'/static/uploads/social/feed';if(!is_dir($dir)&&!mkdir($dir,0775,true))respond(false,['message'=>'Armazenamento indisponível.'],500);$name=bin2hex(random_bytes(20)).'.'.$ext;if(!move_uploaded_file($file['tmp_name'],$dir.'/'.$name))respond(false,['message'=>'Não foi possível salvar a mídia.'],500);return ['../static/uploads/social/feed/'.$name,$type];}
$action=(string)($_GET['action']??$_POST['action']??'overview');
try{
if($action==='feed_public'){$before=(int)($_GET['before']??0);$where='p.id_comunidade IS NULL';$params=[$uid];if($before>0){$where.=' AND p.id_post<?';$params[]=$before;}$s=$pdo->prepare("SELECT p.*,u.nm_usuario,u.is_community_user,(SELECT COUNT(*) FROM social_post_curtidas l WHERE l.id_post=p.id_post) total_curtidas,(SELECT COUNT(*) FROM social_post_comentarios c WHERE c.id_post=p.id_post) total_comentarios,EXISTS(SELECT 1 FROM social_post_curtidas ml WHERE ml.id_post=p.id_post AND ml.id_usuario=?) curtiu FROM social_posts p JOIN usuario u ON u.id_usuario=p.id_usuario WHERE $where ORDER BY p.id_post DESC LIMIT 30");$s->execute($params);respond(true,['posts'=>$s->fetchAll()]);}
if($action==='create_public_post'){$d=$_POST;requireCsrf($d);$text=mb_substr(trim((string)($d['text']??'')),0,4000);[$url,$type]=uploadPostMedia($_FILES['media']??[]);if($text===''&&!$url)respond(false,['message'=>'Escreva algo ou selecione uma foto ou vídeo.'],422);$s=$pdo->prepare('INSERT INTO social_posts(id_comunidade,id_usuario,conteudo,midia_url,midia_tipo) VALUES(NULL,?,?,?,?)');$s->execute([$uid,$text,$url,$type]);respond(true,['id'=>(int)$pdo->lastInsertId(),'message'=>'Publicação criada.']);}
if($action==='edit_post'){$d=input();requireCsrf($d);$post=(int)($d['post']??0);$text=mb_substr(trim((string)($d['text']??'')),0,4000);$s=$pdo->prepare('SELECT midia_url FROM social_posts WHERE id_post=? AND id_usuario=?');$s->execute([$post,$uid]);$media=$s->fetchColumn();if($media===false)respond(false,['message'=>'Publicação não encontrada ou sem permissão para editar.'],404);if($text===''&&empty($media))respond(false,['message'=>'O texto não pode ficar vazio.'],422);$pdo->prepare('UPDATE social_posts SET conteudo=?,editado_em=CURRENT_TIMESTAMP WHERE id_post=? AND id_usuario=?')->execute([$text,$post,$uid]);respond(true,['text'=>$text,'message'=>'Publicação atualizada.']);}
if($action==='toggle_like'){$d=input();requireCsrf($d);$post=(int)($d['post']??0);$exists=$pdo->prepare('SELECT 1 FROM social_post_curtidas WHERE id_post=? AND id_usuario=?');$exists->execute([$post,$uid]);if($exists->fetchColumn()){$pdo->prepare('DELETE FROM social_post_curtidas WHERE id_post=? AND id_usuario=?')->execute([$post,$uid]);$liked=false;}else{$insert=$pdo->prepare('INSERT IGNORE INTO social_post_curtidas(id_post,id_usuario) SELECT id_post,? FROM social_posts WHERE id_post=? AND id_comunidade IS NULL');$insert->execute([$uid,$post]);if(!$insert->rowCount())respond(false,['message'=>'Publicação não encontrada.'],404);$liked=true;}$count=$pdo->prepare('SELECT COUNT(*) FROM social_post_curtidas WHERE id_post=?');$count->execute([$post]);respond(true,['liked'=>$liked,'count'=>(int)$count->fetchColumn()]);}
if($action==='comments'){$post=(int)($_GET['post']??0);$s=$pdo->prepare('SELECT c.id_comentario,c.conteudo,c.criado_em,u.id_usuario,u.nm_usuario,u.is_community_user FROM social_post_comentarios c JOIN usuario u ON u.id_usuario=c.id_usuario JOIN social_posts p ON p.id_post=c.id_post WHERE c.id_post=? AND p.id_comunidade IS NULL ORDER BY c.id_comentario LIMIT 100');$s->execute([$post]);respond(true,['comments'=>$s->fetchAll()]);}
if($action==='add_comment'){$d=input();requireCsrf($d);$post=(int)($d['post']??0);$text=mb_substr(trim((string)($d['text']??'')),0,1200);if(mb_strlen($text)<1)respond(false,['message'=>'Escreva um comentário.'],422);$s=$pdo->prepare('INSERT INTO social_post_comentarios(id_post,id_usuario,conteudo) SELECT id_post,?,? FROM social_posts WHERE id_post=? AND id_comunidade IS NULL');$s->execute([$uid,$text,$post]);if(!$s->rowCount())respond(false,['message'=>'Publicação não encontrada.'],404);respond(true,['message'=>'Comentário publicado.']);}
if($action==='overview'){$s=$pdo->prepare("SELECT c.*,u.nm_usuario criador,(SELECT COUNT(*) FROM social_comunidade_membros m WHERE m.id_comunidade=c.id_comunidade AND m.status='ativo') membros FROM social_comunidades c JOIN usuario u ON u.id_usuario=c.id_criador ORDER BY c.criado_em DESC LIMIT 30");$s->execute();$com=$s->fetchAll();$s=$pdo->prepare("SELECT c.*,COALESCE(l.nome,c.nome,(SELECT u2.nm_usuario FROM social_chat_membros om JOIN usuario u2 ON u2.id_usuario=om.id_usuario WHERE om.id_chat=c.id_chat AND om.id_usuario<>cm.id_usuario LIMIT 1)) titulo,(SELECT MAX(m.criado_em) FROM social_mensagens m WHERE m.id_chat=c.id_chat) ultima_mensagem FROM social_chats c JOIN social_chat_membros cm ON cm.id_chat=c.id_chat AND cm.id_usuario=? LEFT JOIN locais l ON l.id_local=c.id_local ORDER BY ultima_mensagem DESC,c.criado_em DESC");$s->execute([$uid]);respond(true,['communities'=>$com,'chats'=>$s->fetchAll(),'canCreateCommunity'=>canCreate($pdo,$uid)]);}
if($action==='search'){$q=trim((string)($_GET['q']??''));$handle=ltrim($q,'@');if(mb_strlen($handle)<2)respond(true,['communities'=>[],'users'=>[]]);if(str_starts_with($q,'@')){$s=$pdo->prepare('SELECT id_usuario,nm_usuario,social_handle,is_community_user FROM usuario WHERE id_usuario<>? AND social_handle=? LIMIT 1');$s->execute([$uid,$handle]);respond(true,['communities'=>[],'users'=>$s->fetchAll()]);}$like='%'.mb_substr($handle,0,60).'%';$communityLike='%'.mb_substr($q,0,60).'%';$s=$pdo->prepare('SELECT id_comunidade,nome,descricao,privada FROM social_comunidades WHERE nome LIKE ? LIMIT 12');$s->execute([$communityLike]);$c=$s->fetchAll();$s=$pdo->prepare('SELECT id_usuario,nm_usuario,social_handle,is_community_user FROM usuario WHERE id_usuario<>? AND (nm_usuario LIKE ? OR social_handle LIKE ?) ORDER BY (social_handle=?) DESC,nm_usuario LIMIT 12');$s->execute([$uid,$like,$like,$handle]);respond(true,['communities'=>$c,'users'=>$s->fetchAll()]);}
if($action==='create_community'){$d=input();requireCsrf($d);if(!canCreate($pdo,$uid))respond(false,['message'=>'Apenas usuários comunitários e administradores podem criar comunidades.'],403);$name=trim((string)($d['name']??''));$desc=trim((string)($d['description']??''));if(mb_strlen($name)<3||mb_strlen($desc)<10)respond(false,['message'=>'Informe nome e descrição válidos.'],422);$slug=preg_replace('/[^a-z0-9]+/','-',strtolower(iconv('UTF-8','ASCII//TRANSLIT',$name)?:$name)).'-'.bin2hex(random_bytes(3));$pdo->beginTransaction();$s=$pdo->prepare('INSERT INTO social_comunidades(id_criador,nome,slug,descricao,privada) VALUES(?,?,?,?,?)');$s->execute([$uid,$name,$slug,$desc,!empty($d['private'])]);$id=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO social_comunidade_membros VALUES(?,?,'dono','ativo',CURRENT_TIMESTAMP)")->execute([$id,$uid]);$pdo->commit();respond(true,['id'=>$id,'message'=>'Comunidade criada. Você já é o administrador e integrante ativo.']);}
if($action==='join_community'){$d=input();requireCsrf($d);$id=(int)($d['id']??0);$s=$pdo->prepare("INSERT INTO social_comunidade_membros(id_comunidade,id_usuario,status) SELECT id_comunidade,?,IF(privada,'pendente','ativo') FROM social_comunidades WHERE id_comunidade=? ON DUPLICATE KEY UPDATE status=IF(status IN ('ativo','bloqueado'),status,VALUES(status))");$s->execute([$uid,$id]);$status=$pdo->prepare('SELECT status FROM social_comunidade_membros WHERE id_comunidade=? AND id_usuario=?');$status->execute([$id,$uid]);$value=(string)$status->fetchColumn();respond(true,['status'=>$value,'message'=>$value==='pendente'?'Solicitação enviada para aprovação.':'Você entrou na comunidade.']);}
if($action==='start_private'){$d=input();requireCsrf($d);$other=(int)($d['user']??0);if($other<1||$other===$uid)respond(false,['message'=>'Usuário inválido.'],422);$exists=$pdo->prepare('SELECT 1 FROM usuario WHERE id_usuario=?');$exists->execute([$other]);if(!$exists->fetchColumn())respond(false,['message'=>'Usuário não encontrado.'],404);$s=$pdo->prepare("SELECT c.id_chat FROM social_chats c JOIN social_chat_membros a ON a.id_chat=c.id_chat AND a.id_usuario=? JOIN social_chat_membros b ON b.id_chat=c.id_chat AND b.id_usuario=? WHERE c.tipo='privado' LIMIT 1");$s->execute([$uid,$other]);$id=(int)$s->fetchColumn();if(!$id){$pdo->beginTransaction();$pdo->prepare("INSERT INTO social_chats(tipo,id_criador) VALUES('privado',?)")->execute([$uid]);$id=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO social_chat_membros(id_chat,id_usuario) VALUES(?,?),(?,?)")->execute([$id,$uid,$id,$other]);$pdo->commit();}respond(true,['id'=>$id]);}
if($action==='feed'){$id=(int)($_GET['community']??0);$access=$pdo->prepare('SELECT c.id_comunidade,c.id_criador,c.nome,c.descricao,c.privada,m.status FROM social_comunidades c LEFT JOIN social_comunidade_membros m ON m.id_comunidade=c.id_comunidade AND m.id_usuario=? WHERE c.id_comunidade=?');$access->execute([$uid,$id]);$community=$access->fetch();if(!$community)respond(false,['message'=>'Comunidade não encontrada.'],404);if((int)$community['privada']===1&&($community['status']??'')!=='ativo')respond(false,['message'=>'Solicitação enviada. Aguarde a aprovação para acessar esta comunidade privada.'],403);$s=$pdo->prepare('SELECT p.*,u.nm_usuario,u.is_community_user FROM social_posts p JOIN usuario u ON u.id_usuario=p.id_usuario WHERE p.id_comunidade=? ORDER BY p.criado_em DESC LIMIT 100');$s->execute([$id]);respond(true,['community'=>$community,'posts'=>$s->fetchAll()]);}
if($action==='post'){$d=$_POST;requireCsrf($d);$id=(int)($d['community']??0);$text=mb_substr(trim((string)($d['text']??'')),0,4000);$s=$pdo->prepare("SELECT c.id_criador,EXISTS(SELECT 1 FROM social_comunidade_membros m WHERE m.id_comunidade=c.id_comunidade AND m.id_usuario=? AND m.status='ativo') membro FROM social_comunidades c WHERE c.id_comunidade=?");$s->execute([$uid,$id]);$community=$s->fetch();if(!$community||!$community['membro'])respond(false,['message'=>'Entre na comunidade para publicar.'],403);$hasMedia=isset($_FILES['media'])&&($_FILES['media']['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_NO_FILE;if($hasMedia&&(int)$community['id_criador']!==$uid)respond(false,['message'=>'Apenas o criador da comunidade pode publicar fotos ou vídeos nela.'],403);[$url,$type]=$hasMedia?uploadPostMedia($_FILES['media'],true):[null,null];if($text===''&&!$url)respond(false,['message'=>'Escreva algo ou selecione uma foto ou vídeo.'],422);$pdo->prepare('INSERT INTO social_posts(id_comunidade,id_usuario,conteudo,midia_url,midia_tipo) VALUES(?,?,?,?,?)')->execute([$id,$uid,$text,$url,$type]);respond(true,['id'=>(int)$pdo->lastInsertId(),'message'=>'Publicado.']);}
if($action==='messages'){$chat=(int)($_GET['chat']??0);member($pdo,$chat,$uid);$after=(int)($_GET['after']??0);if($after>0){$s=$pdo->prepare('SELECT m.*,u.nm_usuario FROM social_mensagens m JOIN usuario u ON u.id_usuario=m.id_usuario WHERE m.id_chat=? AND m.id_mensagem>? ORDER BY m.id_mensagem LIMIT 100');$s->execute([$chat,$after]);}else{$s=$pdo->prepare('SELECT recent.* FROM (SELECT m.*,u.nm_usuario FROM social_mensagens m JOIN usuario u ON u.id_usuario=m.id_usuario WHERE m.id_chat=? ORDER BY m.id_mensagem DESC LIMIT 100) recent ORDER BY recent.id_mensagem');$s->execute([$chat]);}respond(true,['messages'=>$s->fetchAll()]);}
if($action==='send'){$d=$_POST;requireCsrf($d);$chat=(int)($d['chat']??0);member($pdo,$chat,$uid);$text=mb_substr(trim((string)($d['text']??'')),0,4000);$kind=in_array(($d['kind']??''),['imagem','sticker'],true)?$d['kind']:'nenhum';[$url,$mime,$size]=uploadMedia($_FILES['media']??[],$kind==='sticker'?'sticker':'imagem');if($text===''&&!$url)respond(false,['message'=>'Digite uma mensagem ou envie uma mídia.'],422);$s=$pdo->prepare('INSERT INTO social_mensagens(id_chat,id_usuario,texto,tipo_anexo,anexo_url,mime_type,tamanho_bytes) VALUES(?,?,?,?,?,?,?)');$s->execute([$chat,$uid,$text,$url?$kind:'nenhum',$url,$mime,$size]);respond(true,['id'=>(int)$pdo->lastInsertId()]);}
if($action==='edit_message'){$d=input();requireCsrf($d);$message=(int)($d['message']??0);$text=mb_substr(trim((string)($d['text']??'')),0,4000);$s=$pdo->prepare('SELECT id_chat,anexo_url FROM social_mensagens WHERE id_mensagem=? AND id_usuario=?');$s->execute([$message,$uid]);$row=$s->fetch();if(!$row)respond(false,['message'=>'Mensagem não encontrada ou sem permissão para editar.'],404);member($pdo,(int)$row['id_chat'],$uid);if($text===''&&empty($row['anexo_url']))respond(false,['message'=>'O texto não pode ficar vazio.'],422);$pdo->prepare('UPDATE social_mensagens SET texto=?,editado_em=CURRENT_TIMESTAMP WHERE id_mensagem=? AND id_usuario=?')->execute([$text,$message,$uid]);respond(true,['text'=>$text,'message'=>'Mensagem atualizada.']);}
if($action==='places'){$s=$pdo->query("SELECT id_local,nome,tipo,descricao,logradouro,numero,bairro,cidade,uf,cep,latitude,longitude,imagem_principal,acessibilidades FROM locais WHERE status='aprovado' ORDER BY nome");respond(true,['places'=>$s->fetchAll()]);}
respond(false,['message'=>'Ação inválida.'],400);
}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();error_log($e->getMessage());respond(false,['message'=>'Módulo Social indisponível. Execute a migração 20260912_social.sql.'],500);}
