<?php
declare(strict_types=1);
session_start();
require_once __DIR__ . '/configs/config.php';
require_once __DIR__ . '/configs/social_schema.php';
if (empty($_SESSION['usuario_id'])) { header('Location: Login.php?redirect=chats.php'); exit; }
ensureSocialSchema($pdo);
$uid = (int)$_SESSION['usuario_id'];
$statement = $pdo->prepare('SELECT nm_usuario,social_handle,foto_perfil,tp_usuario,is_community_user FROM usuario WHERE id_usuario=?');
$statement->execute([$uid]);
$me = $statement->fetch();
if (!$me) { session_destroy(); header('Location: Login.php'); exit; }
$_SESSION['usuario_nome'] = $me['nm_usuario'];
$_SESSION['usuario_tipo'] = $me['tp_usuario'];
$isAdmin = strcasecmp(trim((string)$me['tp_usuario']), 'Administrador') === 0;
$canCreate = $isAdmin || !empty($me['is_community_user']);
if (empty($_SESSION['social_csrf'])) $_SESSION['social_csrf'] = bin2hex(random_bytes(24));
?>
<!doctype html>
<html lang="pt-BR">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
  <title>Chats | LibrasHub</title>
  <link rel="icon" href="../static/images/librashub-logo.png">
  <link rel="stylesheet" href="../static/css/style.css">
  <link rel="stylesheet" href="../static/css/app-shell.css">
  <link rel="stylesheet" href="../static/css/sidebar.css">
  <link rel="stylesheet" href="../static/css/social.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css">
</head>
<body class="app-shell app-dashboard social-chat-page">
<?php $sidebarId = 'sidebarMenu'; include __DIR__ . '/partials/sidebar.php'; ?>
<main class="content" id="conteudo-principal">
  <div class="social-layout">
    <aside class="social-left" aria-label="Conversas">
      <div class="social-brand">
        <div class="social-brand__row">
          <div><h1>Chats</h1><small>Conversas e comunidades</small></div>
          <?php if ($canCreate): ?><button class="icon-button" id="createCommunity" type="button" aria-label="Criar comunidade" title="Criar comunidade"><i class="fa-solid fa-plus"></i></button><?php endif; ?>
        </div>
        <a class="chat-feed-link" href="social.php"><i class="fa-solid fa-arrow-left"></i>Voltar para o feed</a>
        <div class="social-search"><i class="fa-solid fa-magnifying-glass"></i><input id="globalSearch" type="search" placeholder="Nome da comunidade ou pessoa" aria-label="Buscar comunidade ou usuário"><div class="search-results" id="searchResults"></div></div>
      </div>
      <div class="social-tabs" role="tablist" aria-label="Tipos de conversa"><button class="social-tab is-active" type="button" data-list="communities">Comunidades</button><button class="social-tab" type="button" data-list="private">Chats privados</button></div>
      <div class="social-list" id="socialList"></div>
    </aside>
    <section class="social-main">
      <header class="social-toolbar">
        <div class="social-toolbar__title"><button class="icon-button social-back" id="chatBack" type="button" hidden aria-label="Voltar"><i class="fa-solid fa-arrow-left"></i></button><h2 id="chatTitle">Comunidades</h2></div>
        <button class="ui-button ui-button--secondary community-manage-button" id="communityManageButton" type="button" hidden><i class="fa-solid fa-gear"></i>Gerenciar</button>
      </header>
      <div class="social-content">
        <div class="social-welcome is-active" id="welcome"><div class="social-welcome__inner"><div class="social-welcome__icon"><i class="fa-solid fa-comments"></i></div><h2>Suas conversas em um só lugar.</h2><p>Escolha uma comunidade ou inicie um chat privado.</p></div></div>
        <div class="chat-view" id="chatView">
          <div class="messages" id="messages" aria-live="polite"></div>
          <form class="composer" id="messageForm" enctype="multipart/form-data">
            <div class="reply-preview" id="replyPreview" hidden><div><strong id="replyAuthor"></strong><span id="replyText"></span></div><button class="icon-button" id="cancelReply" type="button" aria-label="Cancelar resposta"><i class="fa-solid fa-xmark"></i></button></div>
            <div class="composer-preview" id="messagePreview" hidden></div>
            <div class="media-menu"><label class="icon-button" title="Enviar imagem"><i class="fa-solid fa-image"></i><input id="imageInput" type="file" accept="image/jpeg,image/png,image/webp,image/gif" hidden></label><label class="icon-button" title="Enviar figurinha"><i class="fa-solid fa-note-sticky"></i><input id="stickerInput" type="file" accept="image/png,image/webp,image/gif" hidden></label></div>
            <textarea id="messageText" rows="1" maxlength="4000" placeholder="Escreva uma mensagem" aria-label="Mensagem"></textarea>
            <button class="icon-button composer-send" type="submit" aria-label="Enviar"><i class="fa-solid fa-paper-plane"></i></button>
          </form>
        </div>
        <div class="community-view" id="communityView"></div>
      </div>
    </section>
  </div>
</main>

<?php if ($canCreate): ?>
<div class="social-dialog" id="communityDialog" role="dialog" aria-modal="true" aria-labelledby="communityDialogTitle">
  <form class="social-dialog__card ui-card social-form" id="communityForm" enctype="multipart/form-data">
    <div class="social-dialog__head"><h2 id="communityDialogTitle">Criar comunidade</h2><button type="button" class="icon-button" data-close aria-label="Fechar"><i class="fa-solid fa-xmark"></i></button></div>
    <div class="ui-field"><label for="communityName">Nome</label><input id="communityName" name="name" maxlength="100" required></div>
    <div class="ui-field"><label for="communityDescription">Descrição</label><textarea id="communityDescription" name="description" minlength="10" maxlength="500" required></textarea></div>
    <div class="ui-field"><label for="communityImage">Foto da comunidade</label><input id="communityImage" name="image" type="file" accept="image/jpeg,image/png,image/webp"><small>JPG, PNG ou WebP, até 5 MB.</small></div>
    <div class="selected-media-preview" id="communityCreatePreview" hidden></div>
    <label class="social-checkbox"><input type="checkbox" name="private" value="1">Comunidade privada</label>
    <div id="communityStatus" role="status"></div><button class="ui-button" type="submit">Criar comunidade</button>
  </form>
</div>
<?php endif; ?>

<div class="social-dialog" id="editDialog" role="dialog" aria-modal="true" aria-labelledby="editDialogTitle">
  <form class="social-dialog__card ui-card social-form" id="editForm">
    <div class="social-dialog__head"><h2 id="editDialogTitle">Editar conteúdo</h2><button type="button" class="icon-button" data-close aria-label="Fechar"><i class="fa-solid fa-xmark"></i></button></div>
    <div class="ui-field"><label for="editText">Texto</label><textarea id="editText" name="text" maxlength="4000"></textarea></div>
    <div id="editStatus" role="status"></div><div class="dialog-actions"><button type="button" class="ui-button ui-button--secondary" data-close>Cancelar</button><button class="ui-button" type="submit">Salvar alterações</button></div>
  </form>
</div>

<div class="social-dialog" id="chatNoticeDialog" role="dialog" aria-modal="true" aria-labelledby="chatNoticeTitle">
  <div class="social-dialog__card ui-card social-form"><div class="social-dialog__head"><h2 id="chatNoticeTitle">LibrasHub</h2><button type="button" class="icon-button" data-close aria-label="Fechar"><i class="fa-solid fa-xmark"></i></button></div><p id="chatNoticeMessage"></p><button class="ui-button" type="button" data-close>Entendi</button></div>
</div>

<div class="social-dialog" id="confirmDialog" role="dialog" aria-modal="true" aria-labelledby="confirmTitle">
  <div class="social-dialog__card ui-card social-form"><div class="social-dialog__head"><h2 id="confirmTitle">Confirmar ação</h2><button type="button" class="icon-button" data-confirm="false" aria-label="Fechar"><i class="fa-solid fa-xmark"></i></button></div><p id="confirmMessage"></p><div class="dialog-actions"><button class="ui-button ui-button--secondary" type="button" data-confirm="false">Cancelar</button><button class="ui-button ui-button--danger" type="button" data-confirm="true">Confirmar</button></div></div>
</div>

<div class="social-dialog" id="manageDialog" role="dialog" aria-modal="true" aria-labelledby="manageDialogTitle">
  <div class="social-dialog__card social-dialog__card--wide ui-card">
    <div class="social-dialog__head"><h2 id="manageDialogTitle">Gerenciar comunidade</h2><button type="button" class="icon-button" data-close aria-label="Fechar"><i class="fa-solid fa-xmark"></i></button></div>
    <form class="social-form community-settings-form" id="manageForm" enctype="multipart/form-data" data-owner-only>
      <div class="ui-field"><label for="manageName">Nome</label><input id="manageName" name="name" maxlength="100" required></div>
      <div class="ui-field"><label for="manageDescription">Descrição</label><textarea id="manageDescription" name="description" minlength="10" maxlength="500" required></textarea></div>
      <div class="ui-field"><label for="manageImage">Nova foto da comunidade</label><input id="manageImage" name="image" type="file" accept="image/jpeg,image/png,image/webp"><small>Opcional. JPG, PNG ou WebP, até 5 MB.</small></div>
      <div class="selected-media-preview" id="manageImagePreview" hidden></div>
      <label class="social-checkbox"><input id="managePrivate" type="checkbox" name="private" value="1">Comunidade privada</label>
      <div id="manageStatus" role="status"></div><button class="ui-button" type="submit">Salvar informações</button>
    </form>
    <section class="community-members-panel" aria-labelledby="membersTitle">
      <div class="members-heading"><div><h3 id="membersTitle">Membros</h3><p id="membersHelp">Adicione pelo nome, defina moderadores, aprove solicitações ou remova participantes.</p></div></div>
      <form class="member-add-form" id="memberAddForm" data-owner-only><label class="sr-only" for="memberHandle">Nome do usuário</label><input id="memberHandle" name="handle" placeholder="Nome do usuário" required><button class="ui-button" type="submit"><i class="fa-solid fa-user-plus"></i>Adicionar</button></form>
      <div class="member-view-tabs" role="tablist" aria-label="Gestão de participantes"><button class="member-view-tab is-active" type="button" data-member-view="requests" data-owner-only>Solicitações <span id="requestCount">0</span></button><button class="member-view-tab" type="button" data-member-view="members">Membros</button></div>
      <div id="memberStatus" class="member-status" role="status"></div><div class="community-member-list" id="communityMemberList"></div>
    </section>
  </div>
</div>

<script>
const API='ajax/social_api.php',EVENTS='ajax/social_events.php',CSRF=<?= json_encode($_SESSION['social_csrf']) ?>,ME=<?= $uid ?>;
const REQUESTED_CHAT=Number(new URLSearchParams(location.search).get('chat')||0);
let data={communities:[],chats:[]},tab=new URLSearchParams(location.search).get('tab')==='private'?'private':'communities';
let activeChat=0,activeCommunity=null,source=null,timer,messageSync=null,openedRequestedChat=false,editContext=null,replyingTo=null,communityMembers=[],memberView='requests';
const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
async function api(action,options={}){const response=await fetch(API+'?'+new URLSearchParams({action,...(options.query||{})}),options.fetch);const result=await response.json().catch(()=>({ok:false,message:'Resposta inválida.'}));if(!response.ok||!result.ok)throw new Error(result.message||'Falha na operação.');return result}
function avatar(photo,name,className='social-avatar'){return photo?`<span class="${className}"><img src="${esc(photo)}" alt="Foto de ${esc(name)}"></span>`:`<span class="${className}" aria-hidden="true">${esc(name?.[0]||'U')}</span>`}
function communityAvatar(community,className='social-avatar'){return community.imagem_capa?`<span class="${className}"><img src="${esc(community.imagem_capa)}" alt="Foto da comunidade ${esc(community.nome)}"></span>`:`<span class="${className}" aria-hidden="true"><i class="fa-solid fa-users"></i></span>`}
function showChatNotice(message,title='LibrasHub'){chatNoticeTitle.textContent=title;chatNoticeMessage.textContent=message;chatNoticeDialog.classList.add('is-open')}
let confirmResolver=null;function askConfirmation(message,title='Confirmar ação'){confirmTitle.textContent=title;confirmMessage.textContent=message;confirmDialog.classList.add('is-open');return new Promise(resolve=>{confirmResolver=resolve})}function closeConfirmation(result=false){confirmDialog.classList.remove('is-open');const resolve=confirmResolver;confirmResolver=null;if(resolve)resolve(result)}confirmDialog.addEventListener('click',event=>{const button=event.target.closest('[data-confirm]');if(!button&&event.target!==confirmDialog)return;closeConfirmation(button?.dataset.confirm==='true')});
function setView(id){['welcome','chatView','communityView'].forEach(view=>document.getElementById(view).classList.toggle('is-active',view===id));chatBack.hidden=id==='welcome';document.querySelector('.social-layout').classList.toggle('has-conversation',id!=='welcome');if(id!=='communityView')communityManageButton.hidden=true}
chatBack.addEventListener('click',()=>{if(source)source.close();clearInterval(messageSync);source=null;messageSync=null;activeChat=0;
activeCommunity=null;clearReply();
chatTitle.textContent=tab==='private'?'Chats privados':'Comunidades';setView('welcome')});

async function overview(){try{data=await api('overview');if(REQUESTED_CHAT&&!openedRequestedChat){const requested=data.chats.find(chat=>Number(chat.id_chat)===REQUESTED_CHAT&&chat.tipo==='privado');if(requested){openedRequestedChat=true;tab='private';renderList();await openChat(Number(requested.id_chat),requested.titulo||'Conversa privada');return}}renderList()}catch(error){socialList.innerHTML=`<div class="social-empty">${esc(error.message)}</div>`}}
function renderList(){document.querySelectorAll('.social-tab').forEach(button=>button.classList.toggle('is-active',button.dataset.list===tab));if(tab==='communities'){socialList.innerHTML=data.communities.length?data.communities.map(community=>`<button class="social-item" type="button" data-community="${community.id_comunidade}">${communityAvatar(community)}<span class="social-item__body"><strong>${esc(community.nome)}</strong><small>${community.privada==1?'Privada':'Pública'} · ${Number(community.membros)} membro(s)</small></span></button>`).join(''):'<div class="social-empty">Nenhuma comunidade encontrada.</div>'}else{const chats=data.chats.filter(chat=>chat.tipo==='privado');socialList.innerHTML=chats.length?chats.map(chat=>`<button class="social-item" type="button" data-chat="${chat.id_chat}">${avatar(chat.foto_perfil,chat.titulo)}<span class="social-item__body"><strong>${esc(chat.titulo||'Conversa privada')}</strong><small>Chat privado</small></span></button>`).join(''):'<div class="social-empty">Busque uma pessoa para iniciar uma conversa.</div>'}}
document.querySelector('.social-tabs').addEventListener('click',event=>{const button=event.target.closest('[data-list]');if(!button)return;tab=button.dataset.list;history.replaceState({},'',`chats.php?tab=${tab}`);chatTitle.textContent=tab==='private'?'Chats privados':'Comunidades';setView('welcome');renderList()});
socialList.addEventListener('click',event=>{const community=event.target.closest('[data-community]'),chat=event.target.closest('[data-chat]');if(community)openCommunity(Number(community.dataset.community));if(chat)openChat(Number(chat.dataset.chat),chat.querySelector('strong').textContent)});

function communityMedia(post){if(!post.midia_url)return '';return post.midia_tipo==='video'?`<video class="community-media" controls preload="metadata"><source src="${esc(post.midia_url)}"></video>`:`<img class="community-media" src="${esc(post.midia_url)}" alt="Mídia publicada por ${esc(post.nm_usuario)}" loading="lazy">`}
function communityRoleBadge(role){if(role==='dono')return '<span class="community-role-badge is-owner"><i class="fa-solid fa-crown"></i>Dono</span>';if(role==='moderador')return '<span class="community-role-badge is-moderator"><i class="fa-solid fa-shield-halved"></i>Moderador</span>';return ''}
function renderCommunityPost(post){const canDelete=Number(post.id_usuario)===ME||Boolean(activeCommunity?.canModerate);return `<article class="social-post community-feed-post ui-card" id="community-post-${Number(post.id_post)}" data-community-post="${Number(post.id_post)}"><div class="social-post__head">${avatar(post.foto_perfil,post.nm_usuario,'post-avatar')}<div><a href="perfil.php?id=${Number(post.id_usuario)}">${esc(post.nm_usuario)}</a>${communityRoleBadge(post.papel_comunidade)}<time>${esc(post.criado_em)}${post.editado_em?' · editado':''}</time></div><div class="post-tools">${Number(post.id_usuario)===ME?'<button type="button" class="post-edit" data-edit-community-post aria-label="Editar publicação"><i class="fa-regular fa-pen-to-square"></i>Editar</button>':''}${canDelete?'<button type="button" class="post-delete" data-delete-community-post aria-label="Excluir publicação"><i class="fa-regular fa-trash-can"></i>Excluir</button>':''}</div></div>${post.conteudo?`<p>${esc(post.conteudo)}</p>`:''}${communityMedia(post)}<footer class="community-post-actions"><button type="button" data-community-like class="${Number(post.curtiu)?'is-active':''}" aria-label="Curtir publicação"><i class="fa-${Number(post.curtiu)?'solid':'regular'} fa-heart"></i><span>${Number(post.total_curtidas)}</span></button><button type="button" data-community-comments aria-label="Abrir comentários"><i class="fa-regular fa-comment"></i><span>${Number(post.total_comentarios)}</span></button><button type="button" data-community-share aria-label="Compartilhar publicação"><i class="fa-solid fa-arrow-up-from-bracket"></i><span>Compartilhar</span></button></footer><section class="community-comments" hidden></section></article>`}
function communityCommentTree(comments){const grouped=new Map();comments.forEach(comment=>{const parent=Number(comment.id_comentario_pai)||0;if(!grouped.has(parent))grouped.set(parent,[]);grouped.get(parent).push(comment)});const render=comment=>`<article class="community-comment" data-community-comment="${Number(comment.id_comentario)}"><header><span><a href="perfil.php?id=${Number(comment.id_usuario)}">${esc(comment.nm_usuario)}</a>${communityRoleBadge(comment.papel_comunidade)}</span><time>${esc(comment.criado_em)}</time></header><p>${esc(comment.conteudo)}</p><div class="community-comment-actions"><button type="button" data-community-comment-like class="${Number(comment.curtiu)?'is-active':''}"><i class="fa-${Number(comment.curtiu)?'solid':'regular'} fa-heart"></i><span>${Number(comment.total_curtidas)}</span></button><button type="button" data-community-comment-reply><i class="fa-solid fa-reply"></i>Responder</button></div><form data-community-reply-form hidden><input name="text" maxlength="1200" placeholder="Responder a ${esc(comment.nm_usuario)}" required><button class="ui-button" aria-label="Enviar resposta"><i class="fa-solid fa-paper-plane"></i></button></form><div class="community-comment-children">${(grouped.get(Number(comment.id_comentario))||[]).map(render).join('')}</div></article>`;return (grouped.get(0)||[]).map(render).join('')}
async function refreshCommunityComments(post,id){const box=post.querySelector('.community-comments'),result=await api('comments',{query:{post:id}});box.innerHTML=`<div class="community-comment-list">${communityCommentTree(result.comments)||'<p class="community-comments-empty">Nenhum comentário ainda.</p>'}</div><form data-community-comment-form><input name="text" maxlength="1200" placeholder="Escreva um comentário" required><button class="ui-button" aria-label="Enviar comentário"><i class="fa-solid fa-paper-plane"></i></button></form>`;box.hidden=false;post.querySelector('[data-community-comments] span').textContent=result.comments.length;return result.comments.length}
async function openCommunity(id){if(source)source.close();clearInterval(messageSync);source=null;messageSync=null;activeChat=0;const joined=await api('join_community',{fetch:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({csrf:CSRF,id})}});if(joined.status==='pendente'){showChatNotice(joined.message,'Solicitação enviada');return}const result=await api('feed',{query:{community:id}});activeCommunity={...result.community,role:result.role,canManage:result.canManage,canModerate:result.canModerate};chatTitle.textContent=activeCommunity.nome;communityManageButton.hidden=!result.canModerate;communityManageButton.innerHTML=result.canManage?'<i class="fa-solid fa-gear"></i>Gerenciar':'<i class="fa-solid fa-shield-halved"></i>Moderar';setView('communityView');
communityView.innerHTML=`<div class="community-stream" id="communityStream"><article class="community-hero ui-card"><div class="community-hero__identity">${communityAvatar(activeCommunity,'community-profile-image')}<div><h2>${esc(activeCommunity.nome)}</h2><p>${esc(activeCommunity.descricao)}</p><small>${Number(activeCommunity.membros)} membro(s) · ${activeCommunity.privada==1?'Privada':'Pública'}</small></div></div></article><div class="community-post-list">${result.posts.map(renderCommunityPost).join('')||'<div class="social-empty">Nenhuma publicação ainda.</div>'}</div></div><form class="post-composer post-composer--community ui-card" id="communityPost" enctype="multipart/form-data"><label for="communityMessage">Criar publicação</label><textarea id="communityMessage" name="text" maxlength="4000" placeholder="Compartilhe algo com a comunidade"></textarea><div class="selected-media-preview" id="communityMediaPreview" hidden></div><div class="post-composer__actions"><label class="community-media-button"><i class="fa-regular fa-image"></i>Foto ou vídeo<input id="communityMediaInput" type="file" name="media" accept="image/jpeg,image/png,image/webp,video/mp4" hidden></label><span class="community-post-status" role="status"></span><button class="ui-button" type="submit">Publicar</button></div></form>`;const form=document.getElementById('communityPost'),mediaInput=document.getElementById('communityMediaInput'),mediaPreview=document.getElementById('communityMediaPreview');bindPreview(mediaInput,mediaPreview,true);form.addEventListener('submit',async event=>{event.preventDefault();const status=form.querySelector('.community-post-status'),formData=new FormData(form);status.textContent='Publicando...';formData.append('csrf',CSRF);formData.append('community',id);try{await api('post',{fetch:{method:'POST',body:formData}});await openCommunity(id)}catch(error){status.textContent=error.message}});
communityView.onclick=async event=>{const post=event.target.closest('[data-community-post]');if(!post)return;const postId=Number(post.dataset.communityPost),edit=event.target.closest('[data-edit-community-post]'),remove=event.target.closest('[data-delete-community-post]'),like=event.target.closest('[data-community-like]'),comments=event.target.closest('[data-community-comments]'),share=event.target.closest('[data-community-share]'),reply=event.target.closest('[data-community-comment-reply]'),commentLike=event.target.closest('[data-community-comment-like]');
try{if(edit){const current=post.querySelector(':scope > p')?.textContent||'';openEditor('edit_post',postId,current,()=>openCommunity(id));return}
if(remove){if(!await askConfirmation('Esta publicação e todos os comentários serão excluídos permanentemente.','Excluir publicação'))return;await api('delete_community_post',{fetch:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({csrf:CSRF,post:postId})}});post.remove();showChatNotice('Publicação excluída.','Moderação');return}
if(like){const response=await api('toggle_like',{fetch:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({csrf:CSRF,post:postId})}});like.classList.toggle('is-active',response.liked);like.querySelector('i').className=`fa-${response.liked?'solid':'regular'} fa-heart`;like.querySelector('span').textContent=response.count;return}if(comments){const box=post.querySelector('.community-comments');if(!box.hidden){box.hidden=true;return}await refreshCommunityComments(post,postId);return}if(share){const url=location.origin+location.pathname+'#community-post-'+postId;if(navigator.share)await navigator.share({title:activeCommunity.nome,url});else{await navigator.clipboard.writeText(url);showChatNotice('Link da publicação copiado.','Compartilhar')}return}if(reply){const replyForm=reply.closest('[data-community-comment]').querySelector(':scope > [data-community-reply-form]');replyForm.hidden=!replyForm.hidden;if(!replyForm.hidden)replyForm.elements.text.focus();return}if(commentLike){const comment=commentLike.closest('[data-community-comment]');const response=await api('toggle_comment_like',{fetch:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({csrf:CSRF,post:postId,comment:comment.dataset.communityComment})}});commentLike.classList.toggle('is-active',response.liked);commentLike.querySelector('i').className=`fa-${response.liked?'solid':'regular'} fa-heart`;commentLike.querySelector('span').textContent=response.count}}catch(error){showChatNotice(error.message,'Não foi possível concluir')}};communityView.onsubmit=async event=>{const commentForm=event.target.closest('[data-community-comment-form],[data-community-reply-form]');if(!commentForm)return;event.preventDefault();const post=commentForm.closest('[data-community-post]'),postId=Number(post.dataset.communityPost),parent=commentForm.matches('[data-community-reply-form]')?Number(commentForm.closest('[data-community-comment]').dataset.communityComment):0,button=commentForm.querySelector('button');button.disabled=true;try{await api('add_comment',{fetch:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({csrf:CSRF,post:postId,parent,text:commentForm.elements.text.value})}});await refreshCommunityComments(post,postId)}catch(error){showChatNotice(error.message,'Não foi possível comentar')}finally{button.disabled=false}}}

async function openChat(id,title){activeCommunity=null;communityManageButton.hidden=true;activeChat=id;clearReply();chatTitle.textContent=title;setView('chatView');messages.innerHTML='';if(source)source.close();clearInterval(messageSync);const result=await api('messages',{query:{chat:id}});result.messages.forEach(addMessage);source=new EventSource(EVENTS+'?'+new URLSearchParams({chat:id,after:lastMessage()}));source.addEventListener('message',event=>addMessage(JSON.parse(event.data)));messageSync=setInterval(async()=>{if(activeChat!==id)return;try{const current=await api('messages',{query:{chat:id}});if(activeChat===id)current.messages.forEach(addMessage)}catch(error){}},8000)}
function lastMessage(){return Number(messages.lastElementChild?.dataset.id||0)}
function addMessage(message){if(Number(message.id_chat)!==activeChat)return;let element=messages.querySelector(`[data-id="${message.id_mensagem}"]`);const mine=Number(message.id_usuario)===ME;const quote=message.id_mensagem_resposta?`<button class="message-quote" type="button" data-jump-message="${Number(message.id_mensagem_resposta)}"><strong>${esc(message.resposta_autor||'Mensagem')}</strong><span>${esc(message.resposta_texto||((message.resposta_tipo_anexo&&message.resposta_tipo_anexo!=='nenhum')?'Mídia':'Mensagem indisponível'))}</span></button>`:'';const body=`<div class="message-head">${!mine&&message.foto_perfil?`<img class="message-avatar" src="${esc(message.foto_perfil)}" alt="">`:''}<strong>${esc(message.nm_usuario)}</strong><span class="message-tools"><button type="button" data-reply-message aria-label="Responder mensagem"><i class="fa-solid fa-reply"></i></button>${mine&&message.texto?'<button type="button" data-edit-message aria-label="Editar mensagem"><i class="fa-solid fa-pen"></i></button>':''}</span></div>${quote}${message.anexo_url?`<img src="${esc(message.anexo_url)}" alt="${message.tipo_anexo==='sticker'?'Figurinha':'Imagem enviada'}">`:''}${message.texto?`<p>${esc(message.texto)}</p>`:''}<small class="message-time">${esc(message.criado_em||'')}${message.editado_em?' · editada':''}</small>`;if(element){element.innerHTML=body;return}element=document.createElement('article');element.className='message '+(mine?'is-mine ':'')+(message.tipo_anexo==='sticker'?'is-sticker':'');element.dataset.id=message.id_mensagem;element.dataset.author=message.nm_usuario||'Usuário';element.dataset.text=message.texto||((message.tipo_anexo&&message.tipo_anexo!=='nenhum')?'Mídia':'Mensagem');element.innerHTML=body;messages.appendChild(element);messages.scrollTop=messages.scrollHeight}
function clearReply(){replyingTo=null;replyPreview.hidden=true;replyAuthor.textContent='';replyText.textContent=''}
messageForm.addEventListener('submit',async event=>{event.preventDefault();if(!activeChat)return;const file=stickerInput.files[0]||imageInput.files[0],formData=new FormData();formData.append('csrf',CSRF);formData.append('chat',activeChat);formData.append('text',messageText.value);formData.append('kind',stickerInput.files[0]?'sticker':'imagem');if(replyingTo)formData.append('reply_to',replyingTo.id);if(file)formData.append('media',file);await api('send',{fetch:{method:'POST',body:formData}});messageText.value='';imageInput.value='';stickerInput.value='';clearPreview(messagePreview);clearReply()});
messageText.addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();messageForm.requestSubmit()}});
messages.addEventListener('click',event=>{const jump=event.target.closest('[data-jump-message]');if(jump){const target=messages.querySelector(`[data-id="${jump.dataset.jumpMessage}"]`);if(target){target.scrollIntoView({behavior:'smooth',block:'center'});target.classList.add('is-highlighted');setTimeout(()=>target.classList.remove('is-highlighted'),1400)}return}const reply=event.target.closest('[data-reply-message]');if(reply){const message=reply.closest('[data-id]');replyingTo={id:Number(message.dataset.id),author:message.dataset.author,text:message.dataset.text};replyAuthor.textContent='Respondendo a '+replyingTo.author;replyText.textContent=replyingTo.text;replyPreview.hidden=false;messageText.focus();return}const button=event.target.closest('[data-edit-message]');if(!button)return;const message=button.closest('[data-id]'),current=message.querySelector('p')?.textContent||'';openEditor('edit_message',message.dataset.id,current,result=>{const paragraph=message.querySelector('p');if(paragraph)paragraph.textContent=result.text;message.dataset.text=result.text;const time=message.querySelector('.message-time');if(time&&!time.textContent.includes('editada'))time.textContent+=' · editada'})});
cancelReply.addEventListener('click',clearReply);

function clearPreview(container){container.innerHTML='';container.hidden=true}
function bindPreview(input,container,allowVideo=false,onSelected){input.addEventListener('change',()=>{clearPreview(container);const file=input.files?.[0];if(!file)return;if(file.size>40*1024*1024){input.value='';container.hidden=false;container.textContent='O arquivo excede o limite permitido.';return}const url=URL.createObjectURL(file),isVideo=allowVideo&&file.type.startsWith('video/');container.innerHTML=`${isVideo?`<video src="${url}" controls></video>`:`<img src="${url}" alt="Prévia da mídia selecionada">`}<button type="button" aria-label="Remover mídia"><i class="fa-solid fa-xmark"></i></button>`;container.hidden=false;container.querySelector('button').onclick=()=>{input.value='';URL.revokeObjectURL(url);clearPreview(container)};if(onSelected)onSelected()})}
bindPreview(imageInput,messagePreview,false,()=>{stickerInput.value=''});bindPreview(stickerInput,messagePreview,false,()=>{imageInput.value=''});

globalSearch.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(async()=>{if(globalSearch.value.trim().length<2){searchResults.innerHTML='';return}const result=await api('search',{query:{q:globalSearch.value}});searchResults.innerHTML=[...result.communities.map(community=>`<button class="social-item" type="button" data-search-community="${community.id_comunidade}">${communityAvatar(community)}<span class="social-item__body"><strong>${esc(community.nome)}</strong><small>Comunidade ${community.privada==1?'privada':'pública'}</small></span></button>`),...result.users.map(user=>`<button class="social-item" type="button" data-search-user="${user.id_usuario}" data-user-name="${esc(user.nm_usuario)}">${avatar(user.foto_perfil,user.nm_usuario)}<span class="social-item__body"><strong>${esc(user.nm_usuario)}</strong><small>Usuário do LibrasHub</small></span></button>`)].join('')},250)});
searchResults.addEventListener('click',async event=>{const community=event.target.closest('[data-search-community]'),user=event.target.closest('[data-search-user]');if(community){tab='communities';renderList();await openCommunity(Number(community.dataset.searchCommunity))}if(user){const result=await api('start_private',{fetch:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({csrf:CSRF,user:user.dataset.searchUser})}});tab='private';await overview();renderList();await openChat(result.id,user.dataset.userName)}searchResults.innerHTML=''});
function openEditor(action,id,text,done){editContext={action,id,done};editDialogTitle.textContent=action==='edit_message'?'Editar mensagem':'Editar publicação';editText.value=text;editStatus.textContent='';editDialog.classList.add('is-open');setTimeout(()=>editText.focus(),0)}
editForm.addEventListener('submit',async event=>{event.preventDefault();if(!editContext)return;const submit=event.target.querySelector('[type="submit"]'),payload={csrf:CSRF,text:editText.value};payload[editContext.action==='edit_post'?'post':'message']=editContext.id;submit.disabled=true;editStatus.textContent='Salvando...';try{const result=await api(editContext.action,{fetch:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}}),done=editContext.done;editDialog.classList.remove('is-open');editContext=null;await done(result)}catch(error){editStatus.textContent=error.message}finally{submit.disabled=false}});

<?php if ($canCreate): ?>
createCommunity.addEventListener('click',()=>{communityStatus.textContent='';communityDialog.classList.add('is-open')});bindPreview(communityImage,communityCreatePreview);
communityForm.addEventListener('submit',async event=>{event.preventDefault();const formData=new FormData(event.target);formData.append('csrf',CSRF);communityStatus.textContent='Criando...';try{const result=await api('create_community',{fetch:{method:'POST',body:formData}});event.target.reset();clearPreview(communityCreatePreview);communityDialog.classList.remove('is-open');tab='communities';await overview();await openCommunity(Number(result.id))}catch(error){communityStatus.textContent=error.message}});
<?php endif; ?>

communityManageButton.addEventListener('click',openManagement);bindPreview(manageImage,manageImagePreview);
async function openManagement(){if(!activeCommunity?.canModerate)return;const isOwner=Boolean(activeCommunity.canManage);document.querySelectorAll('[data-owner-only]').forEach(element=>element.hidden=!isOwner);manageDialogTitle.textContent=isOwner?'Gerenciar comunidade':'Moderar comunidade';membersHelp.textContent=isOwner?'Defina moderadores, aprove solicitações ou expulse participantes.':'Fiscalize os membros e expulse usuários comuns quando necessário.';memberView=isOwner?'requests':'members';if(isOwner){manageName.value=activeCommunity.nome;manageDescription.value=activeCommunity.descricao;managePrivate.checked=Number(activeCommunity.privada)===1;manageImage.value='';clearPreview(manageImagePreview)}manageStatus.textContent='';memberStatus.textContent='';manageDialog.classList.add('is-open');await loadMembers()}
function renderMembers(){const owner=Boolean(activeCommunity?.canManage),filtered=communityMembers.filter(member=>memberView==='requests'?member.status==='pendente':member.status!=='pendente');requestCount.textContent=String(communityMembers.filter(member=>member.status==='pendente').length);document.querySelectorAll('[data-member-view]').forEach(button=>button.classList.toggle('is-active',button.dataset.memberView===memberView));communityMemberList.innerHTML=filtered.map(member=>{let actions='';if(member.status==='pendente'&&owner)actions=`<button type="button" class="member-action member-action--approve" data-approve-member="${member.id_usuario}">Aprovar</button><button type="button" class="member-action member-action--remove" data-reject-member="${member.id_usuario}">Recusar</button>`;else if(member.papel==='membro')actions=`${owner?`<button type="button" class="member-action member-action--role" data-set-role="moderador" data-user="${member.id_usuario}"><i class="fa-solid fa-shield-halved"></i>Tornar moderador</button>`:''}<button type="button" class="member-action member-action--remove" data-remove-member="${member.id_usuario}">Expulsar</button>`;else if(member.papel==='moderador'&&owner)actions=`<button type="button" class="member-action" data-set-role="membro" data-user="${member.id_usuario}">Remover moderação</button><button type="button" class="member-action member-action--remove" data-remove-member="${member.id_usuario}">Expulsar</button>`;return `<article class="community-member">${avatar(member.foto_perfil,member.nm_usuario,'member-avatar')}<div><strong>${esc(member.nm_usuario)} ${communityRoleBadge(member.papel)}</strong><small>${esc(member.status)}</small></div><div class="member-actions">${actions}</div></article>`}).join('')||`<div class="social-empty">${memberView==='requests'?'Nenhuma solicitação pendente.':'Nenhum membro nesta lista.'}</div>`}
async function loadMembers(){if(!activeCommunity)return;communityMemberList.innerHTML='<div class="social-empty">Carregando membros...</div>';try{const result=await api('community_members',{query:{community:activeCommunity.id_comunidade}});communityMembers=result.members;renderMembers()}catch(error){communityMemberList.innerHTML=`<div class="ui-alert ui-alert--error">${esc(error.message)}</div>`}}
manageForm.addEventListener('submit',async event=>{event.preventDefault();if(!activeCommunity)return;const id=Number(activeCommunity.id_comunidade),formData=new FormData(event.target);formData.append('csrf',CSRF);formData.append('community',id);manageStatus.textContent='Salvando...';try{await api('update_community',{fetch:{method:'POST',body:formData}});await overview();await openCommunity(id);manageDialog.classList.add('is-open');manageStatus.textContent='Informações atualizadas.'}catch(error){manageStatus.textContent=error.message}});
memberAddForm.addEventListener('submit',async event=>{event.preventDefault();memberStatus.textContent='Adicionando...';try{await api('add_community_member',{fetch:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({csrf:CSRF,community:activeCommunity.id_comunidade,handle:memberHandle.value})}});event.target.reset();memberStatus.textContent='Membro adicionado.';await loadMembers()}catch(error){memberStatus.textContent=error.message}});
document.querySelector('.member-view-tabs').addEventListener('click',event=>{const button=event.target.closest('[data-member-view]');if(!button)return;memberView=button.dataset.memberView;renderMembers()});
communityMemberList.addEventListener('click',async event=>{const approve=event.target.closest('[data-approve-member]'),reject=event.target.closest('[data-reject-member]'),remove=event.target.closest('[data-remove-member]'),roleButton=event.target.closest('[data-set-role]');if(!approve&&!reject&&!remove&&!roleButton)return;const action=roleButton?'set_community_role':approve?'approve_community_member':reject?'reject_community_member':'remove_community_member',user=Number(roleButton?roleButton.dataset.user:approve?approve.dataset.approveMember:reject?reject.dataset.rejectMember:remove.dataset.removeMember);if((reject||remove)&&!await askConfirmation(reject?'Recusar esta solicitação de entrada?':'Expulsar este usuário da comunidade?',reject?'Recusar solicitação':'Expulsar membro'))return;const buttons=event.target.closest('.member-actions')?.querySelectorAll('button')||[];buttons.forEach(button=>button.disabled=true);memberStatus.textContent='Processando...';try{const payload={csrf:CSRF,community:activeCommunity.id_comunidade,user};if(roleButton)payload.role=roleButton.dataset.setRole;const result=await api(action,{fetch:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}});memberStatus.textContent=result.message;await loadMembers();await overview()}catch(error){memberStatus.textContent=error.message;buttons.forEach(button=>button.disabled=false)}});
document.addEventListener('click',event=>{const close=event.target.closest('[data-close]');if(close)close.closest('.social-dialog')?.classList.remove('is-open');if(event.target.classList.contains('social-dialog'))event.target.classList.remove('is-open')});
document.addEventListener('keydown',event=>{if(event.key==='Escape'){if(confirmDialog.classList.contains('is-open'))closeConfirmation(false);document.querySelectorAll('.social-dialog.is-open').forEach(dialog=>dialog.classList.remove('is-open'))}});
overview();
</script>
<script src="../static/js/acessibility.js" defer></script>
</body>
</html>
